name: Build Docker Image and Push to AWS ECR
on:
  push:
    tags:
    - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to docker.io
        # Docker log
      run:  echo ${{ secrets.DOCKERHUB_PWD }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
    - name: Build, tag, and push image to Doker Hub
      env:
        IMAGE_TAG: ${{ GITHUB_REF }}
      run: |
        docker build -t biwed/pdi-base:$IMAGE_TAG .
        docker push biwed/pdi-base:$IMAGE_TAG
